/* Air Tahiti Tools — Alpha Call-Up V2 — supplied parameter list */
(function(){
  // Source: parameter table supplied by the user. ATA/zone are intentionally not inferred when absent from the source.
  const RAW=`
FDAU (DISCRETE)|26AC1|26VAC BUS 1 STATUS|BUS1_26VAC|
FDAU (DISCRETE)|26AC2|26VAC BUS 2 STATUS|BUS2_26VAC|
FDAU (DISCRETE)|26ACS|26VAC STBY BUS STATUS|BUS_STBYAC|
FDAU (DISCRETE)|AC1BS|AC 1 BUS STATUS|AC1BS|
FDR (MFC)|AC1OF|AC BUS 1 OFF|AC_BUS1|
FDAU (DISCRETE)|AC2BS|AC 2 BUS STATUS|AC2BS|
FDR (MFC)|AC2OF|AC BUS 2 OFF|AC_BUS2|
FDAU (DISCRETE)|ACNUM|A/C IDENT [1,2,3,4,5,6,7,8,9]|ACNUM|
DMU|ACTAI|DMU COMPUTED PARAMETERS|ACTAIL1|ACTAIL2
FDAU (DISCRETE)|ACTYP|A/C TYPE [1,2,3,4]|ACTYPE|
FDR (MFC)|ACWB1|ACW BUS 1 OFF|ACW_BUS1|
FDR (MFC)|ACWB2|ACW BUS 2 OFF|ACW_BUS2|
FDR (MFC)|ACWG1|ACW GENERATRICE 1 FAULT|ACW_GEN1|
FDR (MFC)|ACWG2|ACW GENERATRICE 2 FAULT|ACW_GEN2|
TCAS|ADRTM|ADVISORY RATE|ADRTM|
FDAU (DISCRETE)|AFRFT|DE-ICING AIRFRAME FAULT|AIRFRAME_FLT|
FDAU (DISCRETE)|AFRON|DE-ICING AIRFRAME ON|AIRFRAME|
FDAU (DISCRETE)|AGEAR|DISCRETE ALL GEAR|ALL_GEAR|
FDAU (DISCRETE)|AIPRP|PROPELLER ANTI-ICE 1/2|ANTI_ICEPRO1|ANTI_ICEPRO2
DMU AIR|AIR_GROUND|AIR-GROUND CONDITION (MAIN_GEAR_SQ)|MAIN_GEAR_SQ|
CAC|ALTCA|ALTITUDE CAPTURE MODE|ALTCAPT1|ALTCAPT2
FDR (GPS)|ALTI|GPS ALTITUDE|ALTI_GPS1|ALTI_GPS2
FDAU (ANALOG)|AOAL|AOA 1|AOA_L|
FDAU (ANALOG)|AOAR|AOA 2|AOA_R|
FDAU (APM)|APMCS|CRUISE SPEED LOW|APM_CSL|
FDAU (APM)|APMCX|APM CXA/X60S APM CXTH60S|APMCXAC60S|APMCXTH60S
FDAU (APM)|APMCZ|APM CZZ APM GAMMA|APMCZ|APMGAMMA
FDAU (APM)|APMD1|APM ALTITUDE CAPTURE APM ANTI-ICING|APMALTICAPT|APMANTIICING
FDAU (APM)|APMD2|APM DE-ICING APM ICE DETECTOR|APMDEICING|APMICEDETECT
FDAU (APM)|APMDP|APM DEGRADED PERF|APM_DP|
FDAU (APM)|APMFA|APM FAULT DISCRETE COMING FROM FDAU BITE (BITE2)|APM_FAULT|
FDAU (APM)|APMFF|APM FUEL FLOW 1+2|APMFF|
FDAU (APM)|APMFG|APM FLAPS|APMFLAPS|
FDAU (DISCRETE)|APMFT|APM FAULT|APM_FAULT_CAC|
FDAU (APM)|APMIA|APM IAS|APMIAS|
FDAU (APM)|APMIS|INCREASE SPEED|APM_IS|
FDAU (APM)|APMJX|APM JX|APMJX|
FDAU (BITE)|APMMW|MAINTENANCE WORD MPC (APM)|MWMPC_MSB|MWMPC_LSB
FDAU (APM)|APMNP|APM NP1/NP2|APMNP1|APMNP2
FDAU (DISCRETE)|APMON|APM ON/OFF|APM_APM_ON|
FDAU (APM)|APMSA|APM SAT|APMSAT|
FDAU (APM)|APMSP|APMIASTH APM MSIS|APMIASTH|APMMSIS
FDAU (APM)|APMTA|APM TAS APM TRACTION|APMTAS|APMTRACTION
FDAU (DISCRETE)|APMTE|APM TEST ENABLE DISCRETE|APM_TEST_EN|
FDAU (APM)|APMTQ|APM TQ1/TQ2|APMTQ1|APMTQ2
FDAU (APM)|APMV|APM VERSION|APMVERSION|
FDAU (APM)|APMZP|APM ALTITUDE PRESSURE|APMZP|
FDAU (APM)|APMW|APM TOW APM WEIGHT|APMTOW|APMWEIGHT
TCAS|ATCID|4096 IDENT CODE|ATCID|
TCAS|ATCS1|ATC_MODE_S_INPUT_BUS_1|ATCS1|
TCAS|ATCS2|ATC_MODE_S_INPUT_BUS_2|ATCS2|
TCAS|ATTIN|ATTITUDE_INPUT_BUS|ATTIN|
PEC|BETA|BETA|BETA1|BETA2
EEC|BICOE|MAINTENANCE CODE EEC1 MAINTENANCE CODE EEC2|EEC1_CODE|EEC2_CODE
PEC|BICOP|MAINTENANCE CODE PEC1 MAINTENANCE CODE PEC2|PEC1_CODE|PEC2_CODE
EEC|BITRE|TRIM CODE EEC1 TRIM CODE EEC2|EEC1_TRIM|EEC2_TRIM
PEC|BITRP|TRIM CODE PEC1 TRIM CODE PEC2|PECEEC1_TRIM|PECEEC2_TRIM
FDAU (ANALOG)|BKPLO|BRAKE PRESSURE 1|BKPR1|
FDAU (ANALOG)|BKPRO|BRAKE PRESSURE 2|BKPR2|
FDAU (ANALOG)|BKPLI|BRAKE PRESSURE 3|BKPR3|
FDAU (ANALOG)|BKPRI|BRAKE PRESSURE 4|BKPR4|
FDR (MFC)|BLVLL|ENG BLEED VALVE POSITION LH|BL_VALVE_L|
FDR (MFC)|BLVLR|ENG BLEED VALVE POSITION RH|BL_VALVE_R|
FDAU (DISCRETE)|BOOST|BOOST PW127M|BOOST_PW127M|
FDAU (VOR)|BRG|VOR_BEARING|BRG1|BRG2
TCAS|BTINH|BITE_TEST_INHIBIT|BTINH|
CAC|CADC|ADC SELECTION CAPTAIN|CADC1|CADC2
CAC|CAHR|AHRS SELECTION CAPTAIN|CAHR1|CAHR2
TCAS|CCTL|COMBINED_CONTROL|CCTL|
FDAU (ANALOG)|CDL|CURRENT DETECTOR LEFT|CD_L|
FDAU (ANALOG)|CDR|CURRENT DETECTOR RIGHT|CD_R|
TCAS|CFDIU|CFDIU_INPUT_BUS|CFDIU|
FDR (MFC)|CLASO|CLA FUEL SHUT OFF|CLA1_FUELOFF|CLA2_FUELOFF
TCAS|CMDWA|TCAS FAULT SUMMARY WORD|CMDWA|
FDAU (DISCRETE)|CNDN|EFFORT PITCH AXIS (CAPT DOWN)|EF_CAP_N_DO|
FDAU (DISCRETE)|CNUP|EFFORT PITCH AXIS (CAPT UP)|EF_CAP_N_UP|
FDR (FTU)|CPEF|PITCH CAPTAIN AXIS EFFORT|CPEF|
FDAU (DISCRETE)|CPRB|CAPTAIN PROBES DE-ICE SELECTION|CP_PRB_DEICE|
FDAU (DISCRETE)|CPTD|PITCH TRIM DOWN COMMAND CAPTAIN|CP_TRIM_DOWN|
FDAU (DISCRETE)|CPTU|PITCH TRIM UP COMMAND CAPTAIN|CP_TRIM_UP|
FDAU (DISCRETE)|CLBK|CAPT LH PEDAL BRAKE APPLICATION|CP_L_BK|
FDAU (DISCRETE)|CRBK|CAPT RH PEDAL BRAKE APPLICATION|CP_R_BK|
FDR (DU/FMS)|DA|DRIFT ANGLE|DRIFT_ANGLE1|DRIFT_ANGLE2
FDAU (DATE)|DATE|DATE (GPS/CLOCK/DMU/RTC)|FDAU_DATE|
FDAU (DISCRETE)|DC1BS|DC 1 BUS STATUS|DC_BUS1|
FDAU (DISCRETE)|DC2BS|DC 2 BUS STATUS|DC_BUS2|
FDAU (ANALOG)|DCB1|DC BUS 1|DC_B1|
FDAU (ANALOG)|DCB2|DC BUS 2|DC_B2|
FDAU (ANALOG)|DCEMR|DC EMERGENCY BUS|DCEMR|
FDAU (ANALOG)|DCES1|DC ESSENTIAL BUS 1|DCES1|
FDAU (ANALOG)|DCES2|DC ESSENTIAL BUS 2|DCES2|
FDR (MFC)|DCG1|DC GENERATRICE 1 FAULT|DC_GEN1|
FDR (MFC)|DCG2|DC GENERATRICE 2 FAULT|DC_GEN2|
FDR (MFC)|DCGUT|DC GENERATRICE UTILITIES 1&2|DC_GENUT|
FDR (MFC)|DCSTY|DC STBY BUS OFF|DC_STANDBY|
FDAU (DISCRETE)|DIENG|DE-ICING ENGINE 1 & 2 BOOTS FAULT|DEICE_ENG1|DEICE_ENG2
FDAU (DISCRETE)|DILEL|HORNS RUDDER & LH ELEVATOR DE-ICE|DEICE_ELV_L|
FDAU (DISCRETE)|DILWI|LH WINDSHIELD DE-ICE|WIND_DEICE_L|
FDR (MFC)|DIPRP|DE-ICE PROPELLER FAULT 1 & 2|DEICE_PROP1|DEICE_PROP2
FDAU (DISCRETE)|DIREL|HORNS AILERON & RH ELEVATOR DE-ICE|DEICE_ELV_R|
FDAU (DISCRETE)|DIRWI|RH WINDSHIELD DE-ICE|WIND_DEICE_R|
FDR (DME)|DMED|DME DISTANCE|L_DME_DIS1|L_DME_DIS2
TCAS|DNAD|DOWN_ADVISORY|DNAD|
FDR (DU/FMS)|DTK|DESIRED TRACK|DTK1|DTK2
FDR (DU/FMS)|DTM|DISTANCE TO MISSED APP POINT|DTM1|DTM2
FDR (DU)|DU1S|DU1 STATUS|DU1S|
FDR (DU)|DU2S|DU2 STATUS|DU2S|
FDR (DU)|DU3S|DU3 STATUS|DU3S|
FDR (DU)|DU4S|DU4 STATUS|DU4S|
FDR (DU)|DU5S|DU5 STATUS|DU5S|
EEC|E1MRT|EEC ENGINE LEFT FLIGHT TIME AS PW127M|ENG1_127M_FH|
EEC|E1NFL|EEC ENGINE LEFT NUMBER OF FLIGHTS|ENG1_NFLIGHT|
EEC|E1NST|EEC ENGINE LEFT NUMBER OF STARTS|ENG1_NSTARTS|
EEC|E1RGB|EEC ENGINE LEFT REDUCTION GEAR BOX S/N PART 1&2|ENG1_RGB_SN1|ENG1_RGB_SN2
EEC|E1SN|EEC ENGINE LEFT S/N PART 1&2|ENG1_SN1|ENG1_SN2
EEC|E1TM|EEC ENGINE LEFT TURBO MACHINE S/N PART 1&2|ENG1_TM_SN1|ENG1_TM_SN2
EEC|E1TRT|EEC ENGINE LEFT TOTAL FLIGHT TIME ALL ENGINE MODELS|ENG1_TOT_FH|
EEC|E2MRT|EEC ENGINE RIGHT FLIGHT TIME AS PW127M|ENG2_127M_FH|
EEC|E2NFL|EEC ENGINE RIGHT NUMBER OF FLIGHTS|ENG2_NFLIGHT|
EEC|E2NST|EEC ENGINE RIGHT NUMBER OF STARTS|ENG2_NSTARTS|
EEC|E2RGB|EEC ENGINE RIGHT REDUCTION GEAR BOX S/N PART 1&2|ENG2_RGB_SN1|ENG2_RGB_SN2
EEC|E2SN|EEC ENGINE RIGHT S/N PART 1&2|ENG2_SN1|ENG2_SN2
EEC|E2TM|EEC ENGINE RIGHT TURBO MACHINE S/N PART 1&2|ENG2_TM_SN1|ENG2_TM_SN2
EEC|E2TRT|EEC ENGINE RIGHT TOTAL FLIGHT TIME ALL ENGINE MODELS|ENG2_TOT_FH|
FDR (MFC)|EEC1F|EEC 1 FAULT|EEC1_FAULT|
FDR (MFC)|EEC2F|EEC 2 FAULT|EEC2_FAULT|
CAC (HMD)|EVSDH|EFVS DH|EFVS DECISION HEIGHT|
FDAU (DISCRETE)|ENGM1|ENG MODE 1 LEFT|ENG_MOD1_L|ENG_MOD1_R
FDAU (DISCRETE)|ENGM2|ENG MODE 2 LEFT|ENG_MOD2_L|ENG_MOD2_R
FDR (MFC)|ENOVT|ENG OVERTEMP LEFT/RIGHT|ENG_OVERT_L|ENG_OVERT_R
CAC (HMD)|EVSAI|EVS ANTI ICE ACTIVE|EVS ANTI ICE ACTIVE|
CAC (HMD)|HMNUC|EVS NUC ACTIVE|EVS NUC ACTIVE|
FDAU (DU/FMS)|EPE|FMS ESTIMATED POSITION ERROR|EPE1|EPE2
FDAU (DISCRETE)|EVMKR|EVENT MARKER|EVENT|
FDR (GPS)|EWVEL|E/W VELOCITY|EWVEL1|EWVEL2
CAC (HMD)|HMFLA|FLARE PROMPT DISPLAYED|FLARE PROMPT DISPLAYED ON SKYLENS|
CAC (HMD)|FDLP|FLIGHT DIRECTOR LATERAL POSITION|FLIGHT DIRECTOR LATERAL POSITION|
CAC (HMD)|FDVP|FLIGHT DIRECTOR VERTICAL POSITION|FLIGHT DIRECTOR VERTICAL POSITION|
CAC (HMD)|FPVLP|FPV LATERAL POSITION|FPV LATERAL POSITION|
CAC (HMD)|FPVVP|FPV VERTICAL POSITION|FPV VERTICAL POSITION|
FCU|FCUC|FCU CONFIGURATION|FCU_CFG_L|FCU_CFG_R
DMU (FCU)|FF|FUEL FLOW (NORMALIZED IN KG)|FF_L|FF_R
FCU|FFKH|FUEL FLOW (KPH)|FF_KG_L|FF_KG_R
FCU|FFPH|FUEL FLOW (PPH)|FF_LBS_L|FF_LBS_R
FDR (MFC)|FLP0|FLAP COMMAND 0°|FLAP_0|
FDR (MFC)|FLP15|FLAP COMMAND 15°|FLAP_15|
FDR (MFC)|FLP28|FLAP COMMAND 25°/28°|FLAP_28|
FDR (MFC)|FLP33|FLAP COMMAND 33°|FLAP_33|
FDAU (DISCRETE)|FLPAS|TRAILING EDGE FLAP ASSYM|FLAP_ASSY|
FDAU (DU/FMS)|FLT|COMPUTED FLIGHT NUMBER|FLINUM|
FDAU (DU/FMS)|FLT1|FLIGHT NUMBER (CHARACTERS 1 & 2)|FLINUM1|FLINUM2
FDAU (DU/FMS)|FLT2|FLIGHT NUMBER (CHARACTERS 3 & 4)|FLINUM3|FLINUM4
FDAU (DU/FMS)|FLT3|FLIGHT NUMBER (CHARACTERS 5 & 6)|FLINUM5|FLINUM6
FDAU (DU/FMS)|FLT4|FLIGHT NUMBER (CHARACTERS 7 & 8)|FLINUM7|FLINUM8
FDAU (DU/FMS)|FLT5|FLIGHT NUMBER (CHARACTERS 9 & 10)|FLINUM9|FLINUM10
DMU|FLCNT|FLIGHT COUNT (COMPUTED PARAMETER)|FLCNT|
DMU|FM|FLIGHT MODE (COMPUTED PARAMETER)|FLIMOD|
CAC|FOADC|ADC SELECTION F/O|FOADC1|FOADC2
CAC|FOAHR|AHRS SELECTION F/O|FOAHRS1|FOAHRS2
FDAU (DISCRETE)|FOLBK|F/O LH PEDAL BRAKE APPLICATION|PBK_FO_L|
FDAU (DISCRETE)|FONDN|EFFORT PITCH AXIS (F/O DOWN)|EF_FO_N_DO|
FDAU (DISCRETE)|FONUP|EFFORT PITCH AXIS (F/O UP)|EF_FO_N_UP|
FDR (FTU)|FOPEF|PITCH F/O AXIS EFFORT|FOPEF|
FDAU (DISCRETE)|FOPRB|F/O PROBES DE-ICE SELECTION|FO_DEICE_SEL|
FDAU (DISCRETE)|FOPTD|PITCH TRIM DOWN COMMAND F/O|FO_TRIM_DOWN|
FDAU (DISCRETE)|FOPTU|PITCH TRIM UP COMMAND F/O|FO_TRIM_UP|
FDAU (DISCRETE)|FORBK|F/O RH PEDAL BRAKE APPLICATION|PBK_FO_R|
FCU FQK42|FQ42_KG_L|FUEL QUANTITY (ATR42, KG)|FQ42_KG_L|
FCU FQK72|FQ72_KG_L|FUEL QUANTITY (ATR72, KG)|FQ72_KG_L|
FCU FQP42|FQ42_LBS_L|FUEL QUANTITY (ATR42, LBS)|FQ42_LBS_L|
FCU FQP72|FQ72_LBS_L|FUEL QUANTITY (ATR72, LBS)|FQ72_LBS_L|
FDAU (ANALOG)|GLAT|LATERAL ACCELERATION|GLAT|
FDR (AHRS)|GLAT2|LATERAL ACCELERATION|GLAT_AHRS1|GLAT_AHRS2
FDAU (ANALOG)|GLON|LONGITUDINAL ACCELERATION|GLON|
FDR (AHRS)|GLON2|LONGITUDINAL ACCELERATION|GLON_AHRS1|GLON_AHRS2
FDAU|GMT|TIME (GPS/CLOCK/DMU/RTC)|FDAU_UTC|
FDAU (DISCRETE)|GPWSS|GPWS STATUS|GPWS_STATUS|
FDRALL (VOR)|GSLOP|ILS/GLIDE DEVIATION|GSLOP1|GSLOP2
FDR (GPS)|GSPD|SPEED|GSPD1|GSPD2
FDAU (ANALOG)|GVER|VERTICAL ACCELERATION|GVER|
FDR (AHRS)|GVER2|VERTICAL ACCELERATION|GVER_AHRS1|GVER_AHRS2
FDR (DU/FMS)|GW|GROSS WEIGHT|GW1|GW2
FDAU (APM)|GWT|WEIGHT SELECTION (GROSS WEIGHT)|APMTOW|
FDR (MFC)|HALP|HYDRAULIC AUX. LOW PRESS.|HYD_AUX|
FDR (MFC)|HBLP|HYDRAULIC BLUE LOW PRESS.|HYD_BLUE|
FDAU (DISCRETE)|HF|HF|HF|
FDAU (DISCRETE)|HFCTL|AIR FLOW CONTROL|HIGH_FLOW_CT|
FDR (GPS)|HFOM|HORIZ_FIGURE_OF_MERIT|HFOM1|HFOM2
FDR (MFC)|HGLP|HYDRAULIC GREEN LOW PRESS.|HYD_GREEN|
FDR (GPS)|HIL|AUT_HORIZ_INTEG_LIMIT|HIL1|HIL2
FDAU (ANALOG)|HOTEB|HOT EMERGENCY BAT BUS|HOTEB|
FDR (MFC)|HOTMB|HOT MAIN BAT. BUS|HOT_MBAT_BUS|
CAC (HMD)|HMD2|HMD CAT2 APPROACH|HMD CAT2 APPROACH|
FDAU (MFC)|HPBLD|HP AIR BLEED|HP_VALVE_L|HP_VALVE_R
FDAU (ANALOG)|HYBPR|HYDRAULIC BLUE PRESSURE|HYD_BLUE_PR|
FDAU (ANALOG)|HYGPR|HYDRAULIC GREEN PRESSURE|HYD_GREEN_PR|
FDAU (DISCRETE)|IAOA|ICING AOA|ICING_AOA|
FDAU (ADC)|IAS|IAS|IAS1|IAS2
FDAU (DISCRETE)|ICE|ICE DETECTION|ICE_DETECT|
FDR (MFC)|ICPPS|ICE PROPELLERS SLOW|ICE_PROP_SLW|
FDR (MFC)|ICSEL|ICE-BOOTS MODE SELECTION|ICE_MODE_SEL|
FDR (VOR)|IMKR|DISCRETE INNER|IMKR1|IMKR2
TCAS|INTNO|INTRUDER NUMBER|INTNO|
TCAS|INTSL|INTRUDER SENSIBILITY LEVEL|INTSL|
TCAS|ITRNG|INTRUDER RANGE|ITRNG|
CAC|ITT1|ITT 1 LEFT|ITT1_IOMA12|ITT1_IOMA13
CAC|ITT2|ITT 2 RIGHT|ITT2_IOMA22|ITT2_IOMA23
FDR (MFC)|IWINL|ICE-LH SIDE WINDOWS|ICE_WIN_L|
FDR (MFC)|IWINR|ICE-RH SIDE WINDOWS|ICE_WIN_R|
FDR (GPS)|LAT|LATITUDE|LAT1|LAT2
FDR (GPS)|LATF|LATITUDE FINE|LATF1|LATF2
DMU|LATST|RESULT OF LATERAL ACCELERATION TEST AT END OF FLIGHT|LAT_R15_VAL|
FDR (DU/FMS)|LDEV|LATERAL DEVIATION FROM FMS|LDEV1|LDEV2
FDAU (DISCRETE)|LGSEL|L/G SELECTOR|LANDING_GEAR|
DMU|LIGHT|LIGHT TEST|LIGHT_TEST|
TCAS|LOANT|LOWER_ANTENNA|LOANT|
FDR (VOR)|LOC|VOR/LOC DEVIATION|LOC1|LOC2
FDR (GPS)|LONF|LONGITUDE FINE|LONF1|LONF2
FDR (GPS)|LONG|LONGITUDE|LONG1|LONG2
DMU|LONGST|RESULT OF LONGITUDINAL ACCELERATION TEST AT END OF FLIGHT|LON_R15_VAL|
FDAU (DISCRETE)|LOPIT|DISCRETE LOW PITCH 1|LOW_PITCH_LH|LOW_PITCH_RH
CAC|LSCRS|SELECTED COURSE LEFT|LSCRS1|LSCRS2
FDAU (DISCRETE)|LSPLR|LEFT SPOILER POSITION|SPOILER_L|
FDAU (ANALOG)|LTRAI|LH TRAILING EDGE FLAP|TRAILINGEDGE|
CAC (HMD)|LVTO|LVTO|LVT0 (ON/OFF)|
CAC (HMD)|LVTOP|LVTO CUE POSITION|LVTO CURE POSITION|
FDR (ADC)|MACH|MACH NUMBER|MACH1|MACH2
DMU|MALAR|MASTER CAUTION STATUS MASTER WARNING STATUS|MC_STATUS|MW_STATUS
DMU|MARAW|MASTER CAUTION STATUS RAW MASTER WARNING STATUS RAW|MC_STAT_RAW|MW_STAT_RAW
FDR (MFC)|MFC1A|MFC1-A STATUS 1|MFC1A_STATUS|
FDR (MFC)|MFC1B|MFC1-B STATUS|MFC1B_STATUS|
FDR (MFC)|MFC2A|MFC2-A STATUS 1|MFC2A_STATUS|
FDR (MFC)|MFC2B|MFC2-B STATUS|MFC2B_STATUS|
FDAU (DISCRETE)|MGEAR|DISCRETE MAIN GEAR|MAIN_GEAR_SQ|
FDR (AHRS)|MHDG|MAGNETIC HEADING|HEADING_MH1|HEADING_MH2
TCAS|MHIN|MAGNETIC_HEADING_INPUT_BUS|MHIN|
FDR (VOR)|MMKR|DISCRETE MIDDLE|MMKR1|MMKR2
FDAU (DISCRETE)|MWARN|MASTER WARNING|MAST_WARNING|
CAC|MWNEW|MW NEW|MWNEW1|MWNEW2
FDR (DU/FMS)|NAVM|NAVIGATION MODE|NAVM1|NAVM2
FDR (DU/FMS)|NAVP|A/C NAVIGATION PERFORMANCE|NAVP1|NAVP2
DMU (EEC)|NH|NH LEFT/RIGHT (EEC)|NH_L|NH_R
FDAU (FREQ)|NL|NL1 AND NL2|NL_L_FREQ|NL_R_FREQ
FDAU (FREQ)|NP|NP LEFT/RIGHT (FREQUENCY)|NP_L_FREQ|NP_R_FREQ
EEC|NPEEC|NP LEFT/RIGHT (EEC)|NP_L_EEC|NP_R_EEC
FDR (GPS)|NSVEL|N/S VELOCITY|NSVEL1|NSVEL2
CAC|OILPR|OIL PRESSURE|OILPR_L|OILPR_R
CAC|OILT|OIL TEMP|OILTP_L|OILTP_R
FDR (VOR)|OMKR|DISCRETE OUTER|OMKR1|OMKR2
DMU (EEC)|OTORQ|OBJECTIVE TORQUE LEFT/RIGHT|OTQ_L|OTQ_R
FDAU (DISCRETE)|PACKL|PACK AIR FLOW 1|PACK_AIR_L|
FDAU (DISCRETE)|PACKR|PACK AIR FLOW 2|PACK_AIR_R|
FDAU (ADC)|PALT|PRESS ALT|ALT1|ALT2
FDR (MFC)|PBLCK|PROPELLER BRAKE LOCK|PB_LOCK|
FDR (MFC)|PBUNL|PROPELLER BRAKE UNLOCK|PB_UNLOCK|
CAC|PDID|PROC DISPLAYED ID|PDID1|PDID2
FDR (MFC)|PEC1F|PEC 1 FAULT|PEC1_FAULT|
FDR (MFC)|PEC2F|PEC 2 FAULT|PEC2_FAULT|
FDAU (DISCRETE)|PECS|PEC 1 & 2 STATUS|PEC1_STATUS|PEC2_STATUS
FDAU (ANALOG)|PICPL|LH PITCH CTL POSITION|PITCH_CONT_L|
FDAU (ANALOG)|PICPR|RH PITCH CTL POSITION|PITCH_CONT_R|
FDAU (ANALOG)|PISPL|PITCH SURF. POS. LH|PITCH_SURF_L|
FDAU (ANALOG)|PISPR|PITCH SURF. POS. RH|PITCH_SURF_R|
FDR (AHRS)|PITAT|PITCH ATTITUDE|PITCHANGL1|PITCHANGL2
FDAU (ANALOG)|PITRM|PITCH TRIM SURFACE POSITION|PITCH_TRIM_P|
EEC|PLA|PLA|PLA_L|PLA_R
DMU|R02ST|R02 STABILITY STATUS|R02_STAB_ST|
DMU|R02TI|R02 STABILITY TIME IN SECOND|R02_MON_TIME|
DMU|R02EC|R02 STATUS FOR ECTM RECORDING|R02_ECTMSTAT|
DMU|R02RQ|R02 QUALITY OF LAST ECTM RECORDING|R02_REP_QUAL|
DMU|R02NT|R02 FLAG TRUE IF ECTM TIME IS NEW|R02_FGNEWTIM|R02_ECTIMREF
DMU|R03ST|EPORT 3 TROUBLESHOOTING EXCEEDANCE STATUS|EXC_STAT_R03|
TCAS|RA1DF|RA_1_DISPLAY_FAIL_DISCRETE|RA1DF|
TCAS|RA2DF|RA_2_DISPLAY_FAIL_DISCRETE|RA2DF|
RADALT (RADALT)|RABCD|RADIO ALTITUDE 1|RABCD1|RABCD2
FDAU (RADALT)|RABNR|RADIO ALTITUDE 1|RALT1|RALT2
TCAS|RALT1|RADIO_ALT_INPUT_BUS_1|RALT_BUS1|
TCAS|RALT2|RADIO_ALT_INPUT_BUS_2|RALT_BUS2|
RADALT|RALTF|FILTERED VALUE OF RALT|RALT_F|
FDAU (ANALOG)|ROCWP|ROLL CONTROL WHEEL POS.|ROLL_CONT_WH|
FDR (AHRS)|ROLAT|ROLL ATTITUDE|ROL_ATTITUD1|ROL_ATTITUD2
FDR (FTU)|ROLEF|ROLL AXIS EFFORT|ROLEF|
FDAU (ANALOG)|ROLSP|ROLL TRIM SURFACE POSITION|ROLL_TRIM_P|
FDAU (DISCRETE)|ROLTL|ROLL TRIM LH COMMAND|ROLL_TL_CMD|
FDAU (DISCRETE)|ROLTR|ROLL TRIM RH COMMAND|ROLL_TR_CMD|
FDAU (ANALOG)|ROSPL|ROLL SURF. POS. LH|ROLL_SURF_LH|
FDAU (ANALOG)|ROSPR|ROLL SURF. POS. RH|ROLL_SURF_RH|
CAC|RSCRS|SELECTED COURSE RIGHT|RSCRS1|RSCRS2
FDAU (DISCRETE)|RSPLR|RIGHT SPOILER POSITION|SPOILER_R|
MFC|RTRAI|RH TRAILING EDGE FLAP POSITION|TRAILING_R|
CAC|SALT|SELECTED ALTITUDE|SALT1|SALT2
FDR (ADC)|SBARO|SELECTED BARO-SETTING|BAROSELEC1|BAROSELEC2
TCAS|SEMST|SELECTED_MODE_S_TRANSPONDER|SEMST|
TCAS|SENDC|DISPLAY_CONTROL|SENDC|
CAC|SHDG|SELECTED HEADING|SHDG1|SHDG2
CAC|SLDH|SELECTED LEFT DH|SLDH|
TCAS|SLVLC|SENSIBILITY LEVEL|SLVLC|
TCAS|SPI|SPECIAL PULSE IDENTIFIER|SPI|
CAC|SRDH|SELECTED RIGHT DH|SRDH|
CAC|SSPD|SELECTED SPEED|SSPD1|SSPD2
CAC (HMD)|HMDON|SKYLENS STATUS|SKYLENS (ON/OFF)|
CAC (HMD)|HMCVS|SKYLENS CVS|SKYLENS CVS (ON/OFF)|
CAC (HMD)|HMEVS|SKYLENS EVS|SKYLENS EVS (ON/OFF)|
CAC (HMD)|HMDCO|SKYLENS HMD CONNECTED|SKYLENS HMD CONNECTED|
CAC (HMD)|HMSVS|SKYLENS SVS|SKYLENS SVS (ON/OFF)|
CAC (HMD)|HMRNG|SKYLENS SVS RANGE|SKYLENS SVS RANGE|
FDR (MFC)|STICP|STICK SHAKER CAPTAIN|STICK_CAPT|
FDR (MFC)|STIFO|STICK SHAKER FIRST OFFICER|STICK_OFFI|
FDAU (DISCRETE)|STKPU|STICK PUSHER|STICK_PUSHER|
FDAU (DISCRETE)|STPRB|STBY PROBES DE-ICE|STBY_PRB|
FDAU (DISCRETE)|STPTD|PITCH TRIM DOWN COMMAND STAND BY|STBY_TRIM_DOWN|
FDAU (DISCRETE)|STPTU|PITCH TRIM UP COMMAND STAND BY|STBY_TRIM_UP|
CAC|SVSPD|SELECTED VERTICAL SPEED|SVSPD1|SVSPD2
FDR (DU)|SVSDB|SVS CHECK DATABASE STATUS|SVS HEAD-DOWN CHECK DATABASE STATUS|
FDR (DU)|SVSDG|SVS DGD STATUS|SVS HEAD-DOWN DGD STATUS|
FDR (DU)|SVSLO|SVS LOSS STATUS|SVS HEAD-DOWN LOSS STATUS|
FDR (DU)|SVSPO|SVS POSITION SOURCE|SVS HEAD-DOWN POSITION SOURCE|
FDR (DU)|SVSON|SVS STATUS|SVS HEAD-DOWN STATUS (ON/OFF)|
CAC (HMD)|HMRWY|SYNTHETIC RUNWAY DISPLAYED|SKYLENS SYNTHETIC RUNWAY DISPLAYED|
TCAS|TA1DF|TA_1_DISPLAY_FAIL_DISCRETE|TA1DF|
TCAS|TA2DF|TA_2_DISPLAY_FAIL_DISCRETE|TA2DF|
FDR (ADC)|TAS|TRUE AIRSPEED|TAS1|TAS2
FDAU (ADC)|TAT|TAT|TAT1|TAT2
TCAS|TCASF|TCAS_SYSTEM_FAILURE|TCASF|
TCAS|TCUFT|TCAS_COMPUTER_UNIT|TCUFT|
ANALOG|TGAUG|TEMPERATURE GAUGE 1|TEMP1|TEMP2
FDR (AHRS)|THDG|TRUE HEADING|HEADING_TH1|HEADING_TH2
FDAU (TIME)|TIME|TIME (GPS/CLOCK/DMU/RTC)|FDAU_UTC|
FDAU (DISCRETE)|TOCNF|MW T.O CONFIG|TCONFIG_WARN|
EEC|TORQ|TORQUE LEFT/RIGHT|TORQUE_L|TORQUE_R
FDR (GPS)|TRUTK|TRUE TRACK ANGLE|TRUTK1|TRUTK2
TAWS|TWSPU|TAWS STATUS 1 (PART 1)|TWSPU|
TAWS|TWSSR|TAWS STATUS 2 (PART 1)|TWSSR|
TAWS|TWSTT|TERRAIN DISPLAY STATUS PART I|TWSTT|
TCAS|UPAD|RESOLUTION ADVISORY|UPAD|
TCAS|UPANT|UPPER_ANTENNA|UPANT|
DMU|UTAIR|UTC OF MAX VRTG ON AIR UTC OF MIN VRTG ON AIR|UTC_AIR_MAX|UTC_AIR_MIN
DMU|UTGND|UTC OF MAX VRTG ON GROUND|UTC_GND_MAX|
TCAS|VCTL|RESOLUTION ADVISORY|VCTL|
FDR (DU/FMS)|VDEV|VERTICAL DEVIATION FROM FMS|VDEV1|VDEV2
FDR (GPS)|VFOM|VERT_FIGURE_OF_MERIT|VFOM1|VFOM2
FDAU (DISCRETE)|VHF1|VHF 1|VHF1|
FDAU (DISCRETE)|VHF2|VHF 2|VHF2|
FDAU (DISCRETE)|VHF3|VHF 3|VHF3|
VOR|VORFQ|VOR SELECTED FREQUENCY|VORFQ1|VORFQ2
FDR (ADC)|VRATE|VERTICAL RATE|VRATE1|VRATE2
DMU|VRTST|RESULT OF VERTICAL ACCELERATION TEST AT END OF FLIGHT|VERT_R15_VAL|
DMU|VTAIR|MAX “IN FLIGHT” VERTICAL ACCELERATION MIN “IN FLIGHT” VERTICAL ACCELERATION|VRTG_AIR_MAX|VRTG_AIR_MIN
DMU|VTGND|MAX “LANDING” VERTICAL ACCELERATION|VRTG_GND_MAX|
FDR (DU/FMS)|WDIR|WIND DIRECTION|WDIR1|WDIR2
FDR (DU/FMS)|WSPD|WIND SPEED|WSPD1|WSPD2
DISCRETE|XFVLV|X FEED VALVE POSITION|XFEED_VLV|
FDAU (ANALOG)|YAWCP|YAW CONTROL PED. POS.|YAW_CTR_PED|
FDR (FTU)|YAWEF|YAW AXIS EFFORT|YAWEF|
FDAU (ANALOG)|YAWSP|YAW SURFACE POSITION|YAW_SURF_POS|
FDAU (DISCRETE)|YAWTL|YAW TRIM LH COMMAND|YAW_TL_CMD|
FDAU (DISCRETE)|YAWTR|YAW TRIM RH COMMAND|YAW_TR_CMD|
FDAU (ANALOG)|YWTSP|YAW TRIM SURFACE POSITION|YAW_TSURF_POS|
`.trim();

  const rows=RAW.split('\n').map(line=>{const [source,code,name,p1='',p2='']=line.split('|');return {source,code,name,p1,p2};}).filter(x=>x.code);
  const shared=rows.filter(x=>!/^FQ(42|72)_/.test(x.code));
  const data42=shared.concat(rows.filter(x=>/^FQ42_/.test(x.code)));
  const data72=shared.concat(rows.filter(x=>/^FQ72_/.test(x.code)));
  const DATA={'ATR 42':data42,'ATR 72':data72};

  let aircraft='ATR 42',filter='',sortMode='code';
  const esc=s=>String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const root=document.querySelector('main'); if(!root)return;
  root.innerHTML=`
    <section class="alpha-selector-card"><div class="alpha-section-title">✈️ Sélection avion</div><div class="aircraft-tabs" role="tablist">
      <button class="aircraft-tab active" data-aircraft="ATR 42" role="tab"><span>✈️</span><strong>ATR 42</strong><small>42-600</small></button>
      <button class="aircraft-tab" data-aircraft="ATR 72" role="tab"><span>✈️</span><strong>ATR 72</strong><small>72-600</small></button>
    </div></section>
    <section class="alpha-tools-card"><div class="alpha-section-title">🔎 Recherche</div><div class="alpha-search-wrap"><span>⌕</span><input id="alphaSearch" type="search" placeholder="Rechercher un code, une description ou une source…" autocomplete="off"></div>
      <div class="alpha-sort" aria-label="Classement"><button class="sort-btn active" data-sort="code">Code</button><button class="sort-btn" data-sort="source">Source</button><button class="sort-btn" data-sort="name">Description</button></div></section>
    <section class="alpha-results-card"><div class="alpha-results-head"><div><span class="alpha-kicker">ALPHA CALL-UP</span><h2 id="resultsTitle">ATR 42</h2></div><span id="resultCount" class="alpha-count"></span></div><div id="alphaList" class="alpha-list"></div></section>`;
  const list=document.getElementById('alphaList'),search=document.getElementById('alphaSearch'),title=document.getElementById('resultsTitle'),count=document.getElementById('resultCount');
  function render(){const q=filter.trim().toLowerCase();let rows=DATA[aircraft].filter(x=>!q||[x.code,x.name,x.source,x.p1,x.p2].join(' ').toLowerCase().includes(q));rows.sort((a,b)=>sortMode==='source'?a.source.localeCompare(b.source)||a.code.localeCompare(b.code):sortMode==='name'?a.name.localeCompare(b.name)||a.code.localeCompare(b.code):a.code.localeCompare(b.code));title.textContent=aircraft;count.textContent=`${rows.length} codes`;list.innerHTML=rows.length?rows.map(x=>`<article class="alpha-item"><div class="alpha-code">${esc(x.code)}</div><div class="alpha-item-main"><h3>${esc(x.name)}</h3><p>${esc(x.source)}</p><div class="alpha-meta"><span>${esc(x.p1||'—')}</span><span>${esc(x.p2||'')}</span></div></div></article>`).join(''):'<div class="alpha-empty">Aucun résultat pour cette recherche.</div>';}
  document.querySelectorAll('.aircraft-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.aircraft-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');aircraft=btn.dataset.aircraft;render();}));
  document.querySelectorAll('.sort-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.sort-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');sortMode=btn.dataset.sort;render();}));
  search.addEventListener('input',e=>{filter=e.target.value;render();}); render();
})();
