/* Air Tahiti Tools — Fuel Tools v5 */
(function(){"use strict";
const densityInput=document.getElementById("fuelDensity"),densityStatus=document.getElementById("densityStatus"),densityStatusText=document.getElementById("densityStatusText");
const quantity=document.getElementById("fuelQuantity"),from=document.getElementById("fuelUnit"),to=document.getElementById("fuelToUnit"),result=document.getElementById("fuelResult"),resultUnit=document.getElementById("fuelResultUnit");
const onboard=document.getElementById("fuelOnboard"),required=document.getElementById("fuelRequired"),uplift=document.getElementById("fuelUploadResult"),upliftConversions=document.getElementById("upliftConversions"),reset=document.getElementById("resetFuel");
const L_TO_USGAL=0.26417205236,USGAL_TO_L=3.785411784;let density=0;
function valid(v){return v!==""&&Number.isFinite(Number(v))}
function status(){if(!valid(densityInput.value)){density=0;densityStatus.className="density-status status-waiting";densityStatusText.textContent="À renseigner";return}density=Number(densityInput.value);densityStatus.className="density-status "+(density>=.73&&density<=.85?"status-valid":"status-check");densityStatusText.textContent=density>=.73&&density<=.85?"Valide":"À vérifier"}
function convert(v,a,b){if(a===b)return v;if(a==="kg"&&b==="l")return density>0?v/density:null;if(a==="l"&&b==="kg")return v*density;if(a==="l"&&b==="usgal")return v*L_TO_USGAL;if(a==="usgal"&&b==="l")return v*USGAL_TO_L;if(a==="kg"&&b==="usgal"){let l=convert(v,"kg","l");return l==null?null:l*L_TO_USGAL}if(a==="usgal"&&b==="kg"){let l=convert(v,"usgal","l");return density>0?l*density:null}return null}
function name(u){return u==="kg"?"kg":u==="l"?"L":"US gal"}
function calc(){const r=valid(quantity.value)?convert(Number(quantity.value),from.value,to.value):null;result.textContent=r==null?"—":r.toFixed(2);resultUnit.textContent=name(to.value)}
function calcUplift(){if(!valid(onboard.value)||!valid(required.value)){uplift.textContent="0.0";upliftConversions.textContent="— L  •  — US gal";return}const kg=Math.max(0,Number(required.value)-Number(onboard.value));uplift.textContent=kg.toFixed(1);const l=convert(kg,"kg","l"),g=convert(kg,"kg","usgal");upliftConversions.textContent=l==null?"Densité requise":`${l.toFixed(1)} L  •  ${g.toFixed(1)} US gal`}
densityInput.addEventListener("input",function(){status();calc();calcUplift()});densityInput.addEventListener("blur",function(){if(valid(densityInput.value))densityInput.value=Number(densityInput.value).toFixed(4);status();calc();calcUplift()});quantity.addEventListener("input",calc);from.addEventListener("change",calc);to.addEventListener("change",calc);onboard.addEventListener("input",calcUplift);required.addEventListener("input",calcUplift);reset.addEventListener("click",function(){[densityInput,quantity,onboard,required].forEach(e=>e.value="");from.value="kg";to.value="l";status();calc();calcUplift()});status();calc();calcUplift();
})();