/* Air Tahiti Tools — Torque Tools V8 */
const $=id=>document.getElementById(id);
const setups={1:{name:"Standard / rallonge arrière",desc:"Rallonge derrière la clé dynamométrique : aucune correction.",formula:"Couple à lire = couple réel",fields:[],warning:"Aucune correction nécessaire."},2:{name:"Clé adaptatrice en ligne",desc:"Clé adaptatrice dans l’axe de la clé dynamométrique.",formula:"Tlecture = Tréel × L / (L + L1)",fields:["L","L1"],warning:"Mesurer L et L1 sur l’axe de travail."},3:{name:"Clé adaptatrice + rallonge",desc:"Adaptateur et rallonge placés dans l’axe.",formula:"Tlecture = Tréel × L / (L + L1)",fields:["L","L1"],warning:"La rallonge est comprise dans L1."},4:{name:"Rallonge arrière",desc:"Rallonge placée après la poignée de la clé dynamométrique.",formula:"Tlecture = Tréel × (L + L2) / (L + L1 + L2)",fields:["L","L1","L2"],warning:"Mesurer L, L1 et L2 avant utilisation."},5:{name:"Clé adaptatrice à 90°",desc:"Adaptateur perpendiculaire à 90°.",formula:"Tlecture = Tréel",fields:[],warning:"À 90°, aucune correction nécessaire."},6:{name:"Adaptateur déporté",desc:"Adaptateur en forme de déport / crochet.",formula:"Tlecture = Tréel × L / (L + L1)",fields:["L","L1"],warning:"Utiliser la longueur L1 indiquée sur le schéma."},7:{name:"Adaptateur incliné",desc:"Adaptateur avec angle α compris entre 0° et 90°.",formula:"Tlecture = Tréel × L / (L + L1)",fields:["L","L1","ANGLE"],warning:"Pour le montage 7 : 0° < α < 90°. L1 est la projection de L2 : L1 = L2 × cos α."}};
const labels={L:"Longueur clé dynamométrique (L)",L1:"Longueur clé adaptatrice (L1)",L2:"Longueur rallonge (L2)",ANGLE:"Angle α"};
let selected=1;
function renderFields(){const s=setups[selected];$("setupDescription").textContent=s.desc;$("formulaText").textContent=s.formula;$("warningText").textContent=s.warning;$("dimensions").innerHTML=s.fields.map(f=>`<div class="input-group"><label for="field-${f}">${labels[f]}</label><div class="input-with-unit"><input type="number" id="field-${f}" class="input" placeholder="0" min="0" step="0.1"><span class="input-unit">${f==='ANGLE'?'°':'mm'}</span></div></div>`).join("");$("torqueResult").textContent="0.00";$("differenceResult").textContent="0.00";$("resultUnit").textContent=$("torqueUnit").value;$("resultUnit2").textContent=$("torqueUnit").value}
function chooseSetup(n){selected=n;document.querySelectorAll(".setup-card").forEach(c=>c.classList.toggle("selected",Number(c.dataset.setup)===n));$("selectedSetup").textContent=`Montage ${n} — ${setups[n].name}`;renderFields();$("dimensions").scrollIntoView({behavior:"smooth",block:"nearest"})}
function calculate(){const n=Number($("realTorque").value),d=k=>Number($("field-"+k)?.value||0);if(!(n>0)){alert("Entrez un couple réel valide.");return}let v=n;if([2,3,6].includes(selected)&&!(d("L")>0&&d("L1")>0)){alert("Renseignez L et L1.");return}if(selected===4&&!(d("L")>0&&d("L1")>0&&d("L2")>0)){alert("Renseignez L, L1 et L2.");return}if(selected===7&&(!(d("L")>0&&d("L1")>0)||d("ANGLE")<=0||d("ANGLE")>=90)){alert("Pour le montage 7, renseignez L, L1 et un angle α entre 0° et 90°.");return}if([2,3,6].includes(selected))v=n*d("L")/(d("L")+d("L1"));if(selected===4)v=n*(d("L")+d("L2"))/(d("L")+d("L1")+d("L2"));if(selected===7)v=n*d("L")/(d("L")+d("L1"));$("torqueResult").textContent=v.toFixed(2);$("differenceResult").textContent=(v-n).toFixed(2);$("resultUnit").textContent=$("torqueUnit").value;$("resultUnit2").textContent=$("torqueUnit").value}
const factors={"Nm":1,"daN·m":10,"kgf·m":9.80665,"ft·lb":1.3558179483,"in·lb":0.112984829};
function convert(){const el=$("conversionValue"),v=Number(el.value),from=$("conversionFrom").value,to=$("conversionTo").value;$("conversionResultUnit").textContent=to;$("conversionResult").textContent=Number.isFinite(v)&&el.value!==""?(v*factors[from]/factors[to]).toFixed(2):"0.00"}
document.querySelectorAll(".setup-card").forEach(c=>c.addEventListener("click",()=>chooseSetup(Number(c.dataset.setup))));$("calculateTorque").addEventListener("click",calculate);$("torqueUnit").addEventListener("change",()=>{$("resultUnit").textContent=$("torqueUnit").value;$("resultUnit2").textContent=$("torqueUnit").value});$("conversionValue").addEventListener("input",convert);$("conversionFrom").addEventListener("change",convert);$("conversionTo").addEventListener("change",convert);$("resetTorque").addEventListener("click",()=>{$("realTorque").value="";chooseSetup(1);$("conversionValue").value="";$("conversionResult").textContent="0.00"});$("copyTorque").addEventListener("click",async()=>{const text=`Air Tahiti Tools — Torque\nMontage: ${setups[selected].name}\nCouple réel: ${$("realTorque").value} ${$("torqueUnit").value}\nCouple à lire: ${$("torqueResult").textContent} ${$("resultUnit").textContent}`;try{await navigator.clipboard.writeText(text);$("copyTorque").textContent="Copié ✓";setTimeout(()=>$("copyTorque").textContent="Copier le résultat",1500)}catch(e){}});document.addEventListener("keydown",e=>{if(e.key==="Enter"&&e.target.matches("input"))calculate()});chooseSetup(1);